"""
Handle errors generated by server
"""

from aiohttp import web
from cuvette.provisioners import ValidateError as ProvisionValidateError


async def middleware(app, handler):
    async def error_handler(request):
        try:
            return await handler(request)
        except Exception as ex:
            if isinstance(ex, web.Response):
                raise
            elif isinstance(ex, ProvisionValidateError):
                raise web.json_response({'message': str(ex)}, status=400)
            else:
                raise
    return error_handler
